### ISSUE TITLE
How to add it to dependencies ?

### ISSUE THREAD

**Issue by ahmedmoussa8** [andyxialm/ColorDialog#2]
I want to thank you for your effort on this great library.
Now, I'm trying to add it to my dependencies on Android Studio. 
I don't want to add the whole project as a model.
Any Help !

**Comment by tirolel** [comment]
you can add it via:

dependencies {
    compile 'com.github.andyxialm:ColorDialog:fc1804b35a'
}

**Comment by ahmedmoussa8** [comment]
Thanks .

**Comment by paranoiasystem** [comment]
when I add it to my grandle file I get this error:

> Error:(30, 13) Failed to resolve: com.github.andyxialm:ColorDialog:fc1804b35a

**Comment by tirolel** [comment]
@paranoiasystem remember to add: 

repositories {
    maven {
        url "https://jitpack.io"
    }
}

**Comment by andyxialm** [comment]
``` xml
dependencies {
    compile 'com.github.andyxialm:ColorDialog:1.0.0'
}
```
